### ISSUE TITLE
Error while deploying to Azure App service

### ISSUE THREAD

**Issue by vinaysandela** [Azure/webapps-deploy#190] opened 2021-09-02 21:29 UTC
We are trying to Deploy Azure App Service from GitHub Actions using Windows Self-Hosted Action Runner

Using task - https://github.com/Azure/webapps-deploy

workflow - 
    - name: Deploy to Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
       # app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package:  './myapp/PackageTmp'

We are getting below error - 
Deployment Failed with Error: Error: Failed to deploy web package to App Service. SyntaxError: Error parsing E:\actions-runner\AR\_work\_actions\Azure\webapps-deploy\v2\node_modules\tunnel\package.json: Unexpected token < in JSON at position 2

Can you please suggest. 

Thanks

**Comment by BALAGA-GAYATRI** [comment] 2021-09-13 11:13
Hey @vinaysandela Can you please confirm if

- The `app-name` field is commented or uncommented because deployment is going to fail without it.
- Is it running fine on github hosted runners?(windows-latest/ ubuntu-latest)?
-  The` package` path provided is correct or not.

Also please check if the dependencies required by the app are being fulfilled or not. Visit [example workflows](https://github.com/Azure/webapps-deploy#create-azure-web-app-and-deploy-using-github-actions ) for more context. please let us know if it works.

**Comment by BALAGA-GAYATRI** [comment] 2021-09-21 07:00
@vinaysandela any updates on this issue? Can you share your workflow if the issue still persists.

**Comment by rbinder-vg** [comment] 2022-05-12 11:39
@BALAGA-GAYATRI I got the same issue on my self-hosted runners. 

```
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Error: Failed to deploy web package to App Service.
SyntaxError: Error parsing /opt/actions-runner/_work/_actions/azure/webapps-deploy/v2/node_modules/tunnel/package.json: Unexpected token < in JSON at position 2
```

It seems there is a unresolved git diff in the package.json of tunnel in the current
 v2 release.

```
{
<<<<<<< HEAD
  "name": "tunnel",
  "version": "0.0.6",
=======
  "_from": "tunnel@0.0.6",
  "_id": "tunnel@0.0.6",
  "_inBundle": false,
  "_integrity": "sha512-1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg==",
  "_location": "/tunnel",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "tunnel@0.0.6",
    "name": "tunnel",
    "escapedName": "tunnel",
    "rawSpec": "0.0.6",
    "saveSpec": null,
    "fetchSpec": "0.0.6"
  },
  "_requiredBy": [
    "/typed-rest-client"
  ],
  "_resolved": "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz",
  "_shasum": "72f1314b34a5b192db012324df2cc587ca47f92c",
  "_spec": "tunnel@0.0.6",
  "_where": "E:\\Repos\\GHActions\\webapps-deploy\\node_modules\\typed-rest-client",
  "author": {
    "name": "Koichi Kobayashi",
    "email": "koichik@improvement.jp"
  },
  "bugs": {
    "url": "https://github.com/koichik/node-tunnel/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
>>>>>>> 798e43877120eda6a2a690a4f212c545e586ae31
  "description": "Node HTTP/HTTPS Agents for tunneling proxies",
  "devDependencies": {
    "mocha": "^5.2.0",
    "should": "^13.2.3"
  },
  "directories": {
    "lib": "./lib"
  },
  "engines": {
    "node": ">=0.6.11 <=0.7.0 || >=0.7.3"
  },
  "homepage": "https://github.com/koichik/node-tunnel/",
  "keywords": [
    "http",
    "https",
    "agent",
    "proxy",
    "tunnel"
  ],
  "license": "MIT",
  "main": "./index.js",
  "name": "tunnel",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/koichik/node-tunnel.git"
  },
  "scripts": {
    "test": "mocha"
<<<<<<< HEAD
  },
  "devDependencies": {
    "mocha": "^5.2.0",
    "should": "^13.2.3"
  },
  "engines": {
    "node": ">=0.6.11 <=0.7.0 || >=0.7.3"
  }

,"_resolved": "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz"
,"_integrity": "sha512-1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg=="
,"_from": "tunnel@0.0.6"
}
=======
  },
  "version": "0.0.6"
}
>>>>>>> 798e43877120eda6a2a690a4f212c545e586ae31
```

**Comment by WadeParallon** [comment] 2022-05-25 15:11
I've been deploying `webapps-deploy@v2` fine till about 30 days ago then this error started occurring. Looking at files on the server we confirmed that the package.json file looked like @rbinder-vg's file.

Can confirm rolling back to `webapps-deploy@v1` let's us get past this issue.

**Comment by DeLuca-Marco** [comment] 2022-06-15 21:27
I am facing the same issue. And I can confirm @rbinder-vg's finding.

**Comment by ITSWA** [comment] 2022-09-29 22:34
This issue should be re-opened and addressed. I am also facing the same error/problem and have had to resort back to webapps-deploy@v1 to get it working.

**Comment by shpraka** [comment] 2022-12-21 12:09
We have [fixed ](https://github.com/Azure/webapps-deploy/tree/releases/v2/node_modules/tunnel)this issue in our last release, please try using v2 and see if it's working fine. 

Closing this, please re-open or create new issue in case of any issues.

**Closed by shpraka** 2022-12-21 12:09 UTC
Labels: waiting-for-customer, idle
