### ISSUE TITLE
Images input incorrectly marked as required

### ISSUE THREAD

**Issue by jasperfirecai2** [Azure/webapps-deploy#307] opened 2023-03-31 08:18 UTC
https://github.com/Azure/webapps-deploy/blob/05ac4e98bfa0f856e6669624239291c73ca27698/action.yml#L21

The images input for the workflow is marked as required even though it is only valid for certain situations. The action works without using it. Azure docs also don't use this parameter in almost every example. This leads to false positives in validators for workflows

**Comment by benjaminmillhouse** [comment] 2023-04-06 16:46
Duplicate of #302

**Comment by sgollapudi77** [comment] 2023-07-06 05:53
Closing this as the PR #302 is merged now.

**Closed by sgollapudi77** 2023-07-06 05:53 UTC
Labels: dependencies, idle
