### ISSUE TITLE
Deployment Failed, Error: Failed to deploy web package to App Service. Not Found (CODE: 404)

### ISSUE THREAD

**Issue by vimarie** [Azure/webapps-deploy#351] opened 2023-08-03 09:36 UTC
Hello,

i'm using the action with version 2 and i've got an error on some of subscription:

##[debug]Polling for ZIP Deploy URL: [https://my-application.scm.azurewebsites.net:443/api/zipdeploy?isAsync=true&deployer=GITHUB_ZIP_DEPLOY&message=%7B%22type%22%3A%22deployment%22%2C%22sha%22%3A%2295d06efe0f59b3fd0eb81431a266113da7ebed2b%22%2C%22repoName%22%3A%22myorg%2Fmybackend%22%2C%22actor%22%3A%22johndoe%22%2C%22slotName%22%3A%22%22%2C%22commitMessage%22%3A%22%22%7D/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-08-02_13-34-46Z](https://my-application.scm.azurewebsites.net/api/zipdeploy?isAsync=true&deployer=GITHUB_ZIP_DEPLOY&message=%7B%22type%22%3A%22deployment%22%2C%22sha%22%3A%2295d06efe0f59b3fd0eb81431a266113da7ebed2b%22%2C%22repoName%22%3A%22myorg%2Fmybackend%22%2C%22actor%22%3A%22johndoe%22%2C%22slotName%22%3A%22%22%2C%22commitMessage%22%3A%22%22%7D/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-08-02_13-34-46Z)
##[debug]setting affinity cookie ["ARRAffinity=c98e7e9285c7dbb7fa977a8333eee2544318b89fdea1c8072c0ae10c26b5a0f3;Path=/;HttpOnly;Secure;Domain=my-application.scm.azurewebsites.net","ARRAffinitySameSite=c98e7e9285c7dbb7fa977a8333eee2544318b89fdea1c8072c0ae10c26b5a0f3;Path=/;HttpOnly;SameSite=None;Secure;Domain=my-application.scm.azurewebsites.net"]
##[debug][GET] [https://my-application.scm.azurewebsites.net:443/api/zipdeploy?isAsync=true&deployer=GITHUB_ZIP_DEPLOY&message=%7B%22type%22%3A%22deployment%22%2C%22sha%22%3A%2295d06efe0f59b3fd0eb81431a266113da7ebed2b%22%2C%22repoName%22%3A%22myorg%2Fmybackend%22%2C%22actor%22%3A%22johndoe%22%2C%22slotName%22%3A%22%22%2C%22commitMessage%22%3A%22%22%7D/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-08-02_13-34-46Z](https://my-application.scm.azurewebsites.net/api/zipdeploy?isAsync=true&deployer=GITHUB_ZIP_DEPLOY&message=%7B%22type%22%3A%22deployment%22%2C%22sha%22%3A%2295d06efe0f59b3fd0eb81431a266113da7ebed2b%22%2C%22repoName%22%3A%22myorg%2Fmybackend%22%2C%22actor%22%3A%22johndoe%22%2C%22slotName%22%3A%22%22%2C%22commitMessage%22%3A%22%22%7D/api/deployments/latest?
##[debug]Could not parse response body.
##[debug]{}
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Error: Failed to deploy web package to App Service.
Not Found (CODE: 404)

Any idea of the pb?
Regards

**Comment by larts1** [comment] 2023-08-03 10:02
I just start getting this too. Some web apps still deploy fine, but few now gives this every time
```
Run azure/webapps-deploy@v2
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Error: Failed to deploy web package to App Service.
Not Found (CODE: 404)
App Service Application URL: https://***.azurewebsites.net
```
However the deploy seems to actually go through so the issue is just in the action and it's response status.

**Comment by vimarie** [comment] 2023-08-03 15:36
I'll confirm the deployment is ok, in the portal it says ok but the action failed. It's like it's do some polling to get the status of the deployment and it cannot find it. As workaround i use az webapp deploy from cli which works fine.

**Comment by Benjamin-DAGUE** [comment] 2023-08-04 06:35
Same issue here but deployment is working fine despite the error.

**Comment by vimarie** [comment] 2023-08-04 12:28
It seems that MS is deploying new version of app service:
- Non Working AS :  PLATFORM_VERSION = 100.0.7.262
- Working AS :  PLATFORM_VERSION = 100.0.7.203

**Comment by sgollapudi77** [comment] 2023-08-09 10:43
Hi @vimarie @Benjamin-DAGUE @larts1 , based on our investigation we found out a code defect in latest kudu patch which caused the malformed deployment status uri. There was no issue in deployment but while polling the status because of malformed uri the logs were showing 404. 

We have rolled out the fix. Can you please check now?
In case this issue reappears, restarting the site will mitigate the issue.

**Comment by Benjamin-DAGUE** [comment] 2023-08-09 10:47
Hi, it's working for me now , problem solved!
Thanks

**Comment by sgollapudi77** [comment] 2023-08-10 06:28
The issue has been fixed and rolled out. Closing this now, thanks.

**Closed by sgollapudi77** 2023-08-10 06:28 UTC
Labels: bug, waiting-for-customer
