### ISSUE TITLE
Deploy To Azure WebApp runs forever

### ISSUE THREAD

**Issue by facuesr** [Azure/webapps-deploy#140] opened 2021-05-18 13:46 UTC
I'm trying to deploy a nodejs web app to azure and the action stuck in 'Deploy to Azure WebApp'. 

this is my workflow file.

![Screen Shot 2021-05-18 at 10 44 22](https://user-images.githubusercontent.com/29279815/118662060-16459a80-b7c6-11eb-89d8-e6196e9ef4ac.png)

I'm using a linux app service plan.

**Comment by BALAGA-GAYATRI** [comment] 2021-06-11 09:50
@facuesr can you try adding a secret **ACTIONS_STEP_DEBUG** and set the value **true** and see if it helps debug the issue.

**Comment by ehamai** [comment] 2021-06-15 16:21
Hi @facuesr , just curious but is the target app you're trying to deploy to hosted on an ILB ASE by chance?  If so, I'm wondering if this is a duplicate of this issue.  #135

**Comment by JasonFreeberg** [comment] 2021-07-28 22:20
@facuesr -- Were you deploying to an ILB ASE or a site with private endpoints enabled? I'm wondering if the deployment was blocked due to networking restrictions. Let us know!

**Comment by JasonFreeberg** [comment] 2021-07-30 20:08
@facuesr -- Please let us know your site name and if the site had networking features set up that could block access to the site (firewall, ILB ASE, Private Endpoints, Virtual Network, etc.). I'll close this issue if we don't hear back soon.

**Closed** 2021-09-13 11:31 UTC
Labels: performance-issue, idle
