### ISSUE TITLE
Container Registry value isn't parsed in image deployment

### ISSUE THREAD

**Issue by Diego-MX** [Azure/webapps-deploy#262] opened 2022-11-08 17:00 UTC
## The Issue  
The `images` value isn't parsing its corresponding container registry and tag when deploying to the webapp.  
I have:  
```
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images : '${{secrets.ACR_USER}}.azurecr.io/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}'
        app-name : ${{env.WAP_NAME}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
```
And I get the whole `images` value in the `Deployment Center` view in the Azure Portal.  
![image](https://user-images.githubusercontent.com/9877444/200622808-eccf9561-e4c3-410a-8f2a-8f870d04cc95.png)  

This results in a 503 error when reaching the webapp due to the server being unavailable. 

I can fix this manually by cleaning the name to only include `the-app-image`, that is removing `myRegistry.azurecr.io` and  `the-tag`.  While not shown in the picture, these values are indeed captured correctly in their corresponding fields.  

## Possible Causes  

* This started happenning when the team used a _managed identity_ for the application.  I wouldn't know how this affects the `images` value, but it's worth considering.  

* A second possible casue is external.  Since I'm using this Github Axn together with [`mr-smithers-excellent/docker-build-push`][mr-smithers] for building and pushing, it may be the case that some gears aren't matching between the two actions.   

Thank you for looking into it, or let me know if you need further exploration.   

[mr-smithers]: https://github.com/mr-smithers-excellent/docker-build-push

**Comment by kumaraksh1** [comment] 2022-12-29 06:38
Hi @Diego-MX,
Are you facing this issue with GitHub actions deployment or with Azure portal?

You can follow the following document to deploy custom container through Azure Portal
https://learn.microsoft.com/en-us/azure/app-service/quickstart-custom-container?tabs=python&pivots=container-linux-azure-portal

**Comment by shpraka** [comment] 2023-01-31 07:37
@Diego-MX Could you please share if the issue is with github action deployment or with azure portal?  

Do let us know if the above doc didn't help in resolving the issue.

**Comment by shpraka** [comment] 2023-02-24 08:14
closing this as we didn't receive any update from @Diego-MX. Feel free to create new or re-open this issue.

**Closed by shpraka** 2023-02-24 08:14 UTC
Labels: waiting-for-customer, idle
