### ISSUE TITLE
Getting 404 response on event triggered GitHub action

### ISSUE THREAD

**Issue by derek-munday** [Azure/webapps-deploy#245] opened 2022-08-15 22:08 UTC
<img width="609" alt="Screen Shot 2022-08-15 at 6 01 21 PM" src="https://user-images.githubusercontent.com/21251294/184726302-d3a8791e-d52a-4fc7-9dbe-03bbf867c939.png">

webapps-deploy is giving a 404 response when the GitHub workflow is triggered by a push event. Running the exact same workflow manually via the GitHub UI results in a successful deployment of the app to Azure.

The workflow was previously working as expected and has not been changed.

Problem started August 15th 2022.

**Comment by alexandru-travels** [comment] 2022-08-30 19:26
Bump. 
Having this exact same issue, and the workaround is indeed triggering the pipeline's/action run, by making a change through the Github's site.

**Comment by derek-munday** [comment] 2022-08-30 19:35
@alexandru-travels  we experienced this problem on a dev branch that had files and workflows that did not exist within main. We have since pushed the changes to the main branch and have not observed the issue since.

Is your situation similar?

**Comment by alexandru-travels** [comment] 2022-08-30 20:12
@derek-munday 

So this is what I experienced today:

- edited a GitHub action workflow file (_for some arbitrary automated messaging change, through the Github site_) which only exists in our `master` branch, and is setup to be triggered when there's changes detected to the `master`  branch (_this is code I inherited and there's tech debt_)
- pipeline ran, no problems
- created a pull request to merge our `stage` branch into our `master` branch
- pipeline ran and failed on `azure/webapps-deploy@v2`, with the same 404 error that you posted
- I came across your issue here, and decided to manually edit that pipeline file once more, again through the Github site, and then `azure/webapps-deploy@v2` succeeded. 

And so it seems we might be in the same boat. 
We do have a pipeline file in our `master` branch that doesn't exist in our `dev`. 
I will sync both branches up and see if that fixes our issue. 
Surprised that would be the root cause, but thank you for sharing how your worked around it.

**Comment by shpraka** [comment] 2022-09-22 06:53
@derek-munday are you still facing the issue? Do you have any more error logs other than the screenshot you shared?

**Comment by shpraka** [comment] 2022-10-13 06:58
@derek-munday can you share your workflow file so that we can try to reproduce it and debug further?

**Comment by shpraka** [comment] 2022-10-27 09:13
@derek-munday a gentle reminder. We will be closing this issue by 4th November if we don't hear. 

You can always re-open/create new one if issue persists.

**Comment by kumaraksh1** [comment] 2022-11-07 09:06
@derek-munday, we are closing this ticket for now, you can always re-open/create the issue as mentioned by @shpraka.

**Closed by kumaraksh1** 2022-11-07 09:06 UTC
Labels: waiting-for-customer
