### ISSUE TITLE
Error when deploying to Linux App Service

### ISSUE THREAD

**Issue by harvey-k** [Azure/webapps-deploy#89] opened 2020-12-03 17:21 UTC
Reproduction steps:

1) Create a Linux App Service:
https://github.com/Azure/azure-quickstart-templates/tree/master/101-app-service-docs-linux

2) Attempt to deploy via azure/webapps-deploy@v2:
`
Error: Deployment Failed with Error: Error: Action does not support app service with kind linux.
`

The Linux App Service above is defined with a kind value of 'linux', per:
https://github.com/Azure/azure-quickstart-templates/blob/master/101-app-service-docs-linux/azuredeploy.json#L54

Currently, only a kind value of 'app,linux' is supported in actionparameters.ts

**Comment by AmrutaKawade** [comment] 2020-12-28 11:23
@sanchitmehta / @suwatch can you tell if this is something that has changed from the app service end. Earlier the app type used to be 'app,linux'. Has it changed to only 'linux' now, or are both supported or this is documentation bug in app service creation through ARM template?
https://docs.microsoft.com/en-us/azure/app-service/quickstart-arm-template?pivots=platform-linux

**Comment by AmrutaKawade** [comment] 2021-01-07 05:29
As confirmed with app service team `app,linux` is the right value.  you can change kind in your ARM template. Also appservice team is investigating since its working with `linux` kind as well. We will close this issue and linked PR.

**Closed by AmrutaKawade** 2021-01-07 05:29 UTC
Labels: external-dependency
