### ISSUE TITLE
V3 using node.js 16 upgrade to node.js 20 seeing 16 is deprecated

### ISSUE THREAD

**Issue by MV-PDM** [Azure/webapps-deploy#392] opened 2024-01-25 11:47 UTC
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/webapps-deploy@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Does not take a node.js version either
```json
runs:
  using: 'node20'
```

**Comment by surenderssm** [comment] 2024-01-25 14:14
ACK on the need to move to NODE:20. This is in our scope, will keep the forum updated.
cc : @kumaraksh1

**Comment by michealmueller** [comment] 2024-01-25 16:16
i am also running into this today, do we have an ETA or hotfix/workaround or release?

**Comment by RudiSzalai** [comment] 2024-02-05 04:12
It is hard to believe that there is this little interest in this issue. What do other people use to deploy web apps in Azure??

**Comment by jlaundry** [comment] 2024-02-08 20:27
Looks like there are 2x PRs for this: #393 and #397 (both have exactly the same 1-line change, #397 tests have run and passed)

**Comment by VaclavElias** [comment] 2024-02-08 23:27
This needs to be done also for v2. Another reference https://github.com/Azure/webapps-deploy/issues/372

**Comment by DThorpFF** [comment] 2024-02-20 08:17
> Looks like there are 2x PRs for this: #393 and #397 (both have exactly the same 1-line change, #397 tests have run and passed)

Is there an estimated time for when this will be merged?

**Comment by martincostello** [comment] 2024-03-07 16:16
[GitHub Actions; All Actions will run on Node20 instead of Node16 by default](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)

> Following on from our [warning in workflows using Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) we will start enforcing the use of Node20 rather than Node16 on the 13th of May.

**Comment by MV-PDM** [comment] 2024-03-07 18:43
@martincostello:
> [GitHub Actions; All Actions will run on Node20 instead of Node16 by default](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
> 
> > Following on from our [warning in workflows using Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) we will start enforcing the use of Node20 rather than Node16 on the 13th of May.


@surenderssm @kumaraksh please note the above.

**Comment by Piedone** [comment] 2024-03-11 21:33
Duplicate of: https://github.com/Azure/webapps-deploy/issues/372

**Comment by leandromsft** [comment] 2024-03-13 13:10
I´m using v3 and result this warning

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/webapps-deploy@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by peter5000** [comment] 2024-03-21 16:48
Is there any update on this thread? I am having the same issue as leandromsft. I changed azure/webapps-deploy@v2 to azure/webapps-deploy@v3 in my yml file, but it shows the same warning

**Comment by michealmueller** [comment] 2024-03-21 17:14
i got around this issue by creating my own runner and setting it up to accept node 16 rather then node 20


[https://www.romtech.com/wp-content/themes/romtech2021/img/romtech-logo-m.jpg]  Micheal Mueller
DevOps Engineer
814-516-5762
[LinkedIn]<https://www.linkedin.com/company/rom3rehab> [Twitter] <https://twitter.com/ROMTechnologies>
DISCLAIMER: This message is intended for the above named person(s) only and is CONFIDENTIAL AND PROPRIETARY. The information contained in this transmission, including any attachments, may contain privileged and confidential information, including patient information protected by federal and state privacy laws. If you are not the intended recipient, you are hereby notified that any review, dissemination, distribution, or duplication of this communication is strictly prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.
________________________________

**Comment by danielz-nenda** [comment] 2024-04-02 10:00
Submitted a Azure support request regarding this, we'll see if that helps.

**Comment by ShilpiRachna1** [comment] 2024-04-10 05:24
This issue has been fixed for webapps_deploy@v2 and webapps_deploy@v3. I apologise for the delay.

FYI - @MV-PDM , @michealmueller , @RudiSzalai , @danielz-nenda , @peter5000 , @leandromsft , @martincostello , @Piedone , @VaclavElias , @DThorpFF , @jlaundry

**Comment by Piedone** [comment] 2024-04-10 13:35
Great! Shouldn't then this issue and https://github.com/Azure/webapps-deploy/issues/372 be closed?

**Closed** 2024-04-10 16:46 UTC
Labels: need-to-triage
